stages:
  - build
  - deploy

docker-build:
  stage: build
  image: stieneee/docker-in-ubuntu:latest
  services:
    - docker:dind
  before_script:
    - echo CI_PIPELINE_ID $CI_PIPELINE_ID
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get update
    - apt-get install -y nodejs build-essential git
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.vinci.be
    - curl https://install.meteor.com/ | sh
    - mkdir -p /tmp/meteor-build/
  script:
    - npm i
    - meteor build --allow-superuser --directory /tmp/meteor-build/
    - cp Dockerfile /tmp/meteor-build/bundle/
    - cd /tmp/meteor-build/bundle/
    - ls .
    - docker build -t registry.gitlab.vinci.be/niklas.grosse/pfe-api:$CI_PIPELINE_ID .
    - docker push registry.gitlab.vinci.be/niklas.grosse/pfe-api:$CI_PIPELINE_ID
    - docker tag registry.gitlab.vinci.be/niklas.grosse/pfe-api:$CI_PIPELINE_ID registry.gitlab.vinci.be/niklas.grosse/pfe-api:latest
    - docker push registry.gitlab.vinci.be/niklas.grosse/pfe-api:latest